sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
         # Enable sonata.block.service.stats
        sonata.block.service.stats: 
            contexts: [cms]
         # Enable sonata.block.service.share_list
        sonata.block.service.share_list: 
            contexts: [cms]
sonata_admin:
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: top
                class: col-md-12
                type: sonata.block.service.stats
            -
                position: right
                type: sonata.block.service.share_list