fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path: /
    controller: App\Controller\Library\LibraryController::Index

book_list_page:
    path: /catalogue
    controller: App\Controller\Library\LibraryController::BookListPage

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/

app.swagger_ui:
    path: /apidoc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login_check:
    path: /api/login_check
    methods:  [POST]

api_register:
    path: /api/register
    controller: App\Controller\Authentication\AuthController::Register
    methods:  [POST]


