# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.book:
        class: App\Admin\BookAdmin
        arguments: [~, App\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Books, icon: '<i class="fa fa-book"></i>', label: Book core }
        public: true

    admin.book_category:
        class: App\Admin\BookCategoryAdmin
        arguments: [~, App\Entity\BookCategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Books, label: Book categories }
        public: true

    admin.book_comment:
        class: App\Admin\BookCommentAdmin
        arguments: [~, App\Entity\BookComment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Books, label: Book comments }
        public: true

    admin.book_rate:
        class: App\Admin\BookRateAdmin
        arguments: [~, App\Entity\BookRate, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Books, label: Book rates }
        public: true

    admin.notification:
        class: App\Admin\NotificationAdmin
        arguments: [~, App\Entity\Notification, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Notifications, on_top: true, icon: '<i class="fa fa-bell"></i>', label: Notifications }
        public: true

    admin.share:
        class: App\Admin\ShareAdmin
        arguments: [~, App\Entity\Share, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Shares, on_top: true, icon: '<i class="fa fa-share-alt-square"></i>', label: Shares }
        public: true

    admin.topic:
        class: App\Admin\TopicAdmin
        arguments: [~, App\Entity\Topic, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Topics, on_top: true, icon: '<i class="fa fa-file"></i>', label: Topics }
        public: true

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, icon: '<i class="fa fa-users"></i>', group: Users, label: User core }
        public: true

    admin.user_bio:
        class: App\Admin\UserBioAdmin
        arguments: [~, App\Entity\UserBio, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User biography }
        public: true

    admin.user_comment:
        class: App\Admin\UserCommentAdmin
        arguments: [~, App\Entity\UserComment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User comments }
        public: true

    admin.user_library:
        class: App\Admin\UserLibraryAdmin
        arguments: [~, App\Entity\UserLibrary, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User library }
        public: true

    admin.user_rate:
        class: App\Admin\UserRateAdmin
        arguments: [~, App\Entity\UserRate, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Users, label: User rates }
        public: true

    sonata.block.service.stats:
        class: App\Admin\Block\StatsBlockService
        arguments:
            - "sonata.block.service.stats"
            - "@templating"
            - "@sonata.admin.pool"
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
        tags:
            - { name: sonata.block }

    sonata.block.service.share_list:
        class: App\Admin\Block\ShareListService
        arguments:
            - "sonata.block.service.share_list"
            - "@templating"
            - "@sonata.admin.pool"
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
        tags:
            - { name: sonata.block }