fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

index:
    path: /
    controller: App\Controller\Library\LibraryController::Index

book_list_page:
    path: /catalogue
    controller: App\Controller\Library\LibraryController::BookListPage

book_search_page:
    path: /search
    controller: App\Controller\Library\LibraryController::searchBook

